# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73999ac06618e2b75f482c07ff14f7b1a535512f254235aebec3460af9ed9db99e7b0e414f732f03dd69cdbccce34f38d50669143ba60eb58bd4e945f7aaab9a

test:
  secret_key_base: 53f7be79ddb835a7d8c8897caf77a47fffe7586f75fd2895d3283fec29bd54a42a0da814f23b5d3f6a3ec98e774c221b4c426968a4b38f00290b3e202ca15fae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
